language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
    - libdcmtk2-dev
    - libwrap0-dev
    - libjsoncpp-dev
    - libicu-dev
    - zlib1g-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-test-dev
    - dcmtk
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  # JSONCpp conflicts with json-c
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew uninstall json-c; fi
  # Boost is already installed with another version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew unlink boost; brew install boost; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install dcmtk icu4c jsoncpp; fi
  - pip install --user cpp-coveralls
before_script:
  - export SRC_DIR=$PWD
  - mkdir build
  - cd build
  - export BIN_DIR=$PWD
  - CMAKE_CXX_FLAGS="-std=c++11"
  - if [ "${CC}" = "gcc" ]; then CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} --coverage"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGUMENTS="-D ICU_INCLUDE_DIR=/usr/local/opt/icu4c/include/ -D ICU_LIBRARY=/usr/local/opt/icu4c/lib/libicuuc.dylib"; fi
  - cmake -D CMAKE_CXX_FLAGS:STRING="${CMAKE_CXX_FLAGS}" -D CMAKE_BUILD_TYPE:STRING=Debug ${CMAKE_ARGUMENTS} ../
script:
  - make -j $(nproc)
  - export PATH=$PWD/tests/tools:$PATH
  - ../tests/run.sh
after_success:
  - if [ "${CC}" = "gcc" ]; then ${HOME}/.local/bin/coveralls --exclude examples --exclude tests --exclude-pattern '.*CMake[^/]+\.c(?:pp)?' --exclude-pattern "/usr/.*" --root=${SRC_DIR} --build-root ${BIN_DIR} | grep -vP "^File '.*'$" | grep -vP ":creating '.*'$" | grep -vP "^Lines executed:.*" | sed '/^$/d'; fi
