name: Build
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: ${{ matrix.container || matrix.os }}/${{ matrix.packaging }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container: debian:bullseye
            ci_type: deb
          - os: ubuntu-latest
            container: debian:bookworm
            ci_type: deb
            cmake_options: "-DCMAKE_CXX_STANDARD=17"
          - os: ubuntu-latest
            container: ubuntu:focal
            ci_type: deb
          - os: ubuntu-latest
            container: ubuntu:jammy
            ci_type: deb
            cmake_options: "-DCMAKE_CXX_STANDARD=17"
          # - name: "macOS 11 (Big Sur) + Homebrew"
          #   os: macos-11
          #   ci_type: brew
          #   start_worker: ""
          #   worker: ""
          #   stop_worker: ""
    env:
      WORKSPACE: "${{ github.workspace }}"
      CMAKE_OPTIONS: "${{ matrix.cmake_options }}"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v4
      - name: Configure the build
        run: ./.ci/${{ matrix.ci_type}}/install
      - name: Build
        run: ./.ci/${{ matrix.ci_type}}/build
      - name: Run tests
        run: ./.ci/${{ matrix.ci_type}}/post_build
